import 'package:flutter/material.dart';

enum AppLanguage { ru, uz }

class AppState extends ChangeNotifier {
  AppLanguage _language = AppLanguage.ru;

  AppLanguage get language => _language;

  Locale get locale {
    switch (_language) {
      case AppLanguage.ru:
        return const Locale('ru');
      case AppLanguage.uz:
        return const Locale('uz');
    }
  }

  void toggleLanguage() {
    _language = _language == AppLanguage.ru ? AppLanguage.uz : AppLanguage.ru;
    notifyListeners();
  }

  String t(String key) {
    final map = _localizedStrings[_language] ?? {};
    return map[key] ?? key;
  }
}

const Map<AppLanguage, Map<String, String>> _localizedStrings = {
  AppLanguage.ru: {
    'app_name': 'PoCho',
    'phone_auth_title': 'Вход по номеру телефона',
    'phone_hint': 'Номер телефона',
    'continue': 'Продолжить',
    'otp_title': 'Подтверждение кода',
    'otp_subtitle': 'Введите 4-значный код из SMS',
    'otp_sent_to': 'Код отправлен на номер',
    'verify': 'Подтвердить',
    'resend_code': 'Отправить код повторно',
    'resend_in': 'Отправить повторно через',
    'seconds': 'сек',
    'home': 'Главная',
    'delivery': 'Доставка',
    'categories': 'Категории',
    'map': 'Карта',
    'chat': 'Чат',
    'favorites': 'Избранное',
    'profile': 'Профиль',
    'stations_nearby': 'Заправки рядом',
    'global_chat': 'Глобальный чат водителей',
    'language': 'Язык',
    'russian': 'Русский',
    'uzbek': 'Узбекский',
    'help': 'Помощь',
    'login_title': 'Вход и регистрация',
    'phone_instruction': 'Для продолжения введите номер вашего телефона',
    'agreement_text':
        'Регистрируясь в мобильном приложении, вы подтверждаете свое согласие с условиями',
    'offer_link': 'Публичная оферта и политика конфиденциальности',
    'support_title': 'Служба поддержки',
    'support_chat': 'Чат с поддержкой',
    'support_chat_subtitle':
        'Напишите нам в любое удобное время, наши специалисты ответят при первой же возможности',
    'support_welcome': 'Добро пожаловать в чат поддержки',
    'support_welcome_subtitle':
        'Напишите ваш вопрос, и мы обязательно поможем вам',
    'type_message': 'Введите сообщение...',
    'enter_phone_error': 'Введите номер телефона',
    'invalid_phone_error': 'Неверный формат узбекского номера',
    'notifications': 'Уведомления',
    'terms_and_privacy': 'Публичная оферта и политика конфиденциальности',
    'public_offer': 'Публичная оферта',
    'privacy_policy': 'Политика конфиденциальности',
    'contact_info': 'Контактная информация',
    'offer_intro':
        'Настоящая публичная оферта (далее - "Оферта") является официальным предложением PoCho о заключении договора на использование мобильного приложения PoCho на указанных ниже условиях.',
    'offer_terms': '1. Термины и определения',
    'offer_terms_content':
        'Приложение - мобильное приложение PoCho, доступное для скачивания и использования на мобильных устройствах.\n\nПользователь - физическое лицо, использующее Приложение.\n\nСервис - комплекс услуг, предоставляемых через Приложение.',
    'offer_acceptance': '2. Принятие условий',
    'offer_acceptance_content':
        'Используя Приложение, Пользователь подтверждает, что ознакомился с условиями настоящей Оферты, понимает их и принимает безоговорочно. Если Пользователь не согласен с условиями Оферты, он не должен использовать Приложение.',
    'offer_services': '3. Предмет Оферты',
    'offer_services_content':
        'PoCho предоставляет Пользователю возможность использовать Приложение для поиска заправок, ресторанов, СТО, автомоек и электрозаправок, получения информации о ценах, отзывах и других услугах, доступных через Приложение.',
    'offer_responsibility': '4. Ответственность сторон',
    'offer_responsibility_content':
        'PoCho не несет ответственности за точность информации, предоставляемой третьими лицами (заправками, ресторанами и т.д.). Пользователь использует Приложение на свой риск.',
    'offer_changes': '5. Изменение условий',
    'offer_changes_content':
        'PoCho оставляет за собой право изменять условия настоящей Оферты в любое время. Изменения вступают в силу с момента их публикации в Приложении.',
    'privacy_intro':
        'PoCho серьезно относится к защите персональных данных пользователей. Данная политика объясняет, какую информацию мы собираем, как используем и защищаем её.',
    'privacy_data_collection': '1. Сбор данных',
    'privacy_data_collection_content':
        'Мы собираем следующую информацию:\n- Номер телефона (для аутентификации)\n- Данные геолокации (для поиска услуг)\n- Статистика использования\n- Поисковые запросы',
    'privacy_data_usage': '2. Использование данных',
    'privacy_data_usage_content':
        'Собранная информация используется для следующих целей:\n- Предоставление и улучшение услуг\n- Персонализация пользовательского опыта\n- Техническая поддержка\n- Обеспечение безопасности',
    'privacy_data_protection': '3. Защита данных',
    'privacy_data_protection_content':
        'Мы используем современные технологии шифрования и безопасности для защиты данных пользователей. Информация не передается третьим лицам.',
    'privacy_user_rights': '4. Права пользователя',
    'privacy_user_rights_content':
        'Каждый пользователь имеет право:\n- Доступ к своим данным\n- Редактирование данных\n- Удаление данных\n- Отказ от использования данных',
    'privacy_cookies': '5. Cookie и технологии',
    'privacy_cookies_content':
        'Мы используем cookie и аналогичные технологии для сбора статистики использования и улучшения услуг.',
    'contact_intro':
        'Если у вас есть вопросы или предложения, свяжитесь с нами:',
    'contact_email': 'Электронная почта',
    'contact_phone': 'Телефон',
    'contact_address': 'Адрес',
    'contact_address_content': 'г. Ташкент, ул. Мустакиллик, 10',
    'auth_instruction_title': 'Инструкция по авторизации',
    // Главная страница
    'search_stations_hint': 'Поиск заправок...',
    'retry': 'Повторить',
    'no_stations_found': 'Заправки не найдены',
    'removed_from_favorites': 'Удалено из избранного',
    'added_to_favorites': 'Добавлено в избранное',
    'failed_to_change_favorite': 'Не удалось изменить статус избранного',
    'error_changing_favorite': 'Ошибка при изменении избранного',
    // Фильтры
    'filters': 'Фильтры',
    'fuel_type': 'Тип топлива',
    'min_rating': 'Минимальный рейтинг',
    'max_price': 'Максимальная цена',
    'additional': 'Дополнительно',
    'open_24_7': 'Работает круглосуточно',
    'has_promotions': 'Есть акции',
    'reset': 'Сбросить',
    'apply': 'Применить',
    'all': 'Все',
    'price_up_to_10000': 'До 10 000',
    'price_up_to_12000': 'До 12 000',
    'price_up_to_15000': 'До 15 000',
    'price_up_to_20000': 'До 20 000',
    // Рекламные баннеры
    'promo_discount_10': 'Скидка 10% на все виды топлива',
    'promo_until_weekend': 'До конца недели',
    'promo_free_wash': 'Бесплатная мойка при заправке',
    'promo_from_50_liters': 'От 50 литров',
    'promo_bonus_points': 'Бонусные баллы за каждую заправку',
    'promo_accumulate_exchange': 'Накопи и обменяй',
    // Профиль
    'profile_user': 'Пользователь',
    'profile_beginner': 'Новичок',
    'profile_stations_visited': 'Заправок',
    'profile_favorites_count': 'Избранных',
    'profile_rating': 'Рейтинг',
    'profile_load_error': 'Не удалось загрузить профиль',
    'profile_try_again': 'Попробовать снова',
    'profile_balance': 'Баланс',
    'profile_my_orders': 'Мои заказы',
    'profile_main_info': 'Основная информация',
    'profile_name': 'Имя',
    'profile_phone': 'Телефон',
    'profile_email': 'Email',
    'profile_not_specified': 'Не указано',
    'profile_document_verification': 'Верификация документов',
    'profile_passport': 'Паспорт',
    'profile_driving_license': 'Водительские права',
    'profile_settings': 'Настройки',
    'profile_support': 'Техническая поддержка',
    'profile_logout': 'Выйти',
    'profile_select_photo': 'Выберите фото',
    'profile_gallery': 'Галерея',
    'profile_camera': 'Камера',
    'profile_delete_photo': 'Удалить фото',
    'profile_select_passport_photo': 'Выберите фото паспорта',
    'profile_select_license_photo': 'Выберите фото водительских прав',
    'profile_avatar_updated': 'Аватар успешно обновлен',
    'profile_passport_uploaded': 'Фото паспорта успешно загружено',
    'profile_license_uploaded': 'Фото водительских прав успешно загружено',
    'profile_upload_error': 'Ошибка загрузки',
    'profile_image_error': 'Не удалось выбрать изображение',
    'profile_unsupported_format':
        'Поддерживаются только форматы: JPEG, PNG, WEBP',
    'profile_document_not_uploaded': 'Документ не загружен',
    'profile_click_to_upload': 'Нажмите, чтобы загрузить',
    'notifications_enabled': 'Уведомления включены',
    'notifications_disabled': 'Уведомления выключены',
    'auth_instruction_step1_title': 'Введите номер телефона',
    'auth_instruction_step1_description':
        'Введите ваш номер телефона в формате XX XXX XX XX. Убедитесь, что номер указан правильно.',
    'auth_instruction_step2_title': 'Подтвердите номер',
    'auth_instruction_step2_description':
        'Нажмите кнопку "Продолжить" для отправки SMS-кода подтверждения на указанный номер.',
    'auth_instruction_step3_title': 'Введите код подтверждения',
    'auth_instruction_step3_description':
        'Введите код из SMS-сообщения, который придет на ваш телефон. Код действителен в течение ограниченного времени.',
    'auth_instruction_step4_title': 'Готово!',
    'auth_instruction_step4_description':
        'После успешной авторизации вы сможете пользоваться всеми функциями приложения.',
    'error': 'Ошибка',
    // Доставка
    'delivery_location_permission':
        'Для отображения вашего местоположения на карте необходимо разрешение на доступ к геолокации. Пожалуйста, предоставьте разрешение в настройках приложения.',
    'delivery_location_permission_required':
        'Необходимо разрешение на доступ к местоположению',
    'delivery_location_permission_required_full':
        'Необходимо разрешение на доступ к геолокации для отображения вашего местоположения',
    'delivery_finding_location': 'Определение местоположения...',
    'delivery_location_found': 'Местоположение найдено',
    'delivery_location_failed':
        'Не удалось определить местоположение. Проверьте разрешения.',
    'delivery_find_me': 'Найти меня',
    'delivery_from_to': 'Откуда и куда',
    'delivery_from_to_hint':
        'Укажите точки на карте и при необходимости впишите адреса',
    'delivery_from': 'Откуда',
    'delivery_to': 'Куда',
    'delivery_pickup_address': 'Адрес отправления',
    'delivery_delivery_address': 'Адрес получения',
    'delivery_address_hint': 'Город, улица, дом',
    'delivery_map_point': 'Точка на карте',
    'delivery_specify_pickup': 'Укажите адрес отправления или точку на карте',
    'delivery_specify_delivery': 'Укажите адрес получения или точку на карте',
    'delivery_specify_both_points':
        'Укажите точки на карте для обоих адресов, чтобы рассчитать стоимость',
    'delivery_calculate_price': 'Рассчитать стоимость',
    'delivery_change_addresses': 'Изменить адреса',
    'delivery_price': 'Стоимость доставки',
    'delivery_parcel_description': 'Описание посылки',
    'delivery_parcel_description_hint': 'Например: Документы, одежда',
    'delivery_estimated_value': 'Оценочная стоимость (сум)',
    'delivery_optional': 'Необязательно',
    'delivery_create_order': 'Оформить заказ',
    'delivery_order_created': 'Заказ создан',
    'delivery_courier_contact':
        'Курьер свяжется с вами в ближайшее время для уточнения деталей доставки.',
    'delivery_understood': 'Понятно',
    'delivery_failed_to_calculate': 'Не удалось рассчитать стоимость',
    'delivery_failed_to_create': 'Не удалось создать заказ',
    'delivery_my_orders': 'Мои заказы',
    'delivery_no_orders': 'Заказов пока нет',
    'delivery_create_on_map': 'Оформите доставку на карте',
    'delivery_order': 'Заказ',
    'delivery_order_details': 'Детали заказа',
    'delivery_order_not_found': 'Заказ не найден',
    'delivery_timeline': 'Временная шкала',
    'delivery_order_created_status': 'Заказ создан',
    'delivery_accepted_by_driver': 'Принят водителем',
    'delivery_cargo_received': 'Груз получен',
    'delivery_delivered': 'Доставлен',
    'delivery_cancelled': 'Отменен',
    'delivery_address_not_specified': 'Адрес не указан',
    'delivery_cargo_description_label': 'Описание груза',
    'delivery_weight': 'Вес',
    'delivery_volume': 'Объем',
    'delivery_distance': 'Расстояние',
    'delivery_cost': 'Стоимость',
    'delivery_payment_method': 'Способ оплаты',
    'delivery_client_comment': 'Комментарий клиента',
    'delivery_driver_comment': 'Комментарий водителя',
    'delivery_driver': 'Водитель',
    'delivery_cancel_reason': 'Причина отмены',
    'delivery_accept_order': 'Принять заказ',
    'delivery_driver_on_way': 'Водитель едет за заказом',
    'delivery_going_for_order': 'Еду за заказом',
    'delivery_on_way_to_recipient': 'В пути к получателю',
    'delivery_failed_to_deliver': 'Не удалось доставить',
    'delivery_delivered_status': 'Доставлено',
    'delivery_order_successfully_delivered': 'Заказ успешно доставлен',
    'delivery_order_cancelled': 'Заказ отменен',
    'delivery_failed_to_deliver_order': 'Не удалось доставить заказ',
    'delivery_update_status': 'Обновить статус',
    'delivery_cancel_order': 'Отменить заказ',
    'delivery_cancel_reason_optional': 'Причина отмены (необязательно)',
    'delivery_comment_optional': 'Комментарий (необязательно)',
    'delivery_specify_cancel_reason': 'Укажите причину отмены...',
    'delivery_add_comment': 'Добавьте комментарий...',
    'delivery_confirm': 'Подтвердить',
    'delivery_cancel': 'Отмена',
    'delivery_failed_to_load_orders': 'Не удалось загрузить заказы',
    'delivery_failed_to_load_order': 'Не удалось загрузить заказ',
    'delivery_order_accepted': 'Заказ успешно принят!',
    'delivery_failed_to_accept': 'Не удалось принять заказ',
    'delivery_not_approved':
        'Ваша заявка еще не одобрена администратором. Ожидайте проверки документов.',
    'delivery_rejected':
        'Ваша заявка была отклонена администратором. Обратитесь в поддержку.',
    'delivery_blocked':
        'Ваш аккаунт временно заблокирован. Обратитесь в поддержку.',
    'delivery_not_online': 'Вы должны быть онлайн, чтобы принимать заказы.',
    'delivery_already_accepted': 'Этот заказ уже принят другим водителем.',
    'delivery_status_updated': 'Статус заказа обновлен',
    'delivery_failed_to_update_status': 'Не удалось обновить статус',
    'delivery_no_permission_update':
        'У вас нет прав для обновления статуса этого заказа',
    'delivery_invalid_status_transition':
        'Некорректный переход между статусами. Проверьте текущий статус заказа.',
    'delivery_cannot_cancel_after_pickup':
        'Нельзя отменить заказ после получения посылки водителем',
    'delivery_pick_on_map': 'Указать на карте',
    'delivery_map_picker_title': 'Указать на карте',
    'delivery_select': 'Выбрать',
    'delivery_tap_map_to_select': 'Нажмите на карту, чтобы указать точку',
    'delivery_balance': 'Баланс доставки',
    'delivery_current_balance': 'Текущий баланс',
    'delivery_transaction_history': 'История операций',
    'delivery_no_transactions': 'Операций пока нет',
    'delivery_load_more': 'Загрузить ещё',
    'delivery_failed_to_load_balance': 'Не удалось загрузить баланс',
    'delivery_failed_to_load_history': 'Не удалось загрузить историю',
    'delivery_failed_to_load_more': 'Не удалось подгрузить историю',
    'delivery_today': 'Сегодня',
    'delivery_yesterday': 'Вчера',
    'delivery_regions_uzbekistan': 'По регионам Узбекистана',
    'delivery_time_1_3_days': '1-3 дня',
    'delivery_service_fee_text':
        'В стоимость включен сервисный сбор в размере 0% (вместо 3%) от суммы заказа',
    'delivery_go_to_order_form': 'Перейти к форме заказа',
    // Категории
    'category_restaurants': 'Рестораны',
    'category_car_service': 'СТО',
    'category_car_wash': 'Мойки',
    'category_charging_stations': 'Электрозаправки',
    // Фильтры
    'filter_all': 'Все',
    'filter_nearby': 'Ближайшие',
    'filter_with_promotions': 'С акциями',
    'filter_high_rating': 'Высокий рейтинг',
    'filter_with_parking': 'С парковкой',
    'filter_with_wifi': 'С Wi-Fi',
    'filter_cheap': 'Недорогие',
    'filter_premium': 'Премиум',
    'filter_fast_charging': 'Быстрая зарядка',
    'filter_available': 'Доступные',
    'filter_24_7': '24/7',
    // Кухни
    'cuisine_uzbek': 'Узбекская',
    'cuisine_european': 'Европейская',
    'cuisine_japanese': 'Японская',
    'cuisine_italian': 'Итальянская',
    'cuisine_chinese': 'Китайская',
    'cuisine_american': 'Американская',
    'cuisine_french': 'Французская',
    'cuisine_indian': 'Индийская',
    'cuisine_georgian': 'Грузинская',
    // Ценовые диапазоны
    'price_economy': 'Эконом',
    'price_standard': 'Стандарт',
    'price_all_prices': 'Все цены',
    'price_all_powers': 'Все мощности',
    // Другие тексты категорий
    'select_what_you_need_now': 'Выберите, что вам нужно сейчас',
    'search_restaurants': 'Поиск ресторанов...',
    'search_car_service': 'Поиск СТО...',
    'search_car_wash': 'Поиск моек...',
    'search_charging_stations': 'Поиск электрозаправок...',
    'loading_restaurants': 'Загрузка ресторанов...',
    'loading_car_service': 'Загрузка СТО...',
    'loading_car_wash': 'Загрузка моек...',
    'loading_charging_stations': 'Загрузка электрозаправок...',
    'no_restaurants_found': 'Рестораны не найдены',
    'no_car_service_found': 'СТО не найдены',
    'no_car_wash_found': 'Мойки не найдены',
    'no_charging_stations_found': 'Электрозаправки не найдены',
    'cuisine_type': 'Тип кухни',
    'price_range': 'Ценовой диапазон',
    'service_type': 'Тип услуги',
    'try_changing_filters': 'Попробуйте изменить фильтры',
    'on_map': 'На карте',
    'ai_assistant': 'ИИ помощник',
    // ИИ ассистент
    'ai_assistant_title': 'ИИ Помощник',
    'ai_assistant_subtitle': 'Всегда готов помочь',
    'ai_quick_question_cheap_station': 'Где самая дешевая заправка рядом?',
    'ai_quick_question_fast_route': 'Какой маршрут самый быстрый?',
    'ai_quick_question_fuel_quality': 'Расскажи о качестве топлива',
    'ai_quick_question_fuel_saving': 'Советы по экономии топлива',
    'ai_welcome_message':
        'Привет! Я ИИ помощник PoCho. Я помогу вам найти лучшие заправки, построить маршрут, узнать о ценах на топливо и дать советы по экономии. Чем могу помочь?',
    'ai_quick_questions': 'Быстрые вопросы:',
    'ai_ask_question': 'Задайте вопрос...',
    'ai_send': 'Отправить',
    'ai_cancel': 'Отменить',
    'ai_voice_recording': 'Запись голосового сообщения...',
    'ai_voice_message': 'Голосовое сообщение',
    'ai_history': 'История',
    'ai_menu': 'Меню',
    'ai_clear_history': 'Очистить историю',
    'ai_clear_history_confirm': 'Очистить историю?',
    'ai_clear_history_content':
        'Все сообщения будут удалены. Это действие нельзя отменить.',
    'ai_clear_all': 'Очистить все',
    'ai_history_empty': 'История пуста',
    'ai_history_cleared': 'История очищена',
    'ai_feedback': 'Оставить отзыв',
    'ai_help': 'Помощь',
    'ai_dialog_history': 'История диалогов',
    'ai_dialog_search_stations': 'Поиск заправок',
    'ai_dialog_fuel_saving': 'Советы по экономии',
    'ai_dialog_route': 'Построение маршрута',
    // Глобальный чат
    'global_chat_online': 'Онлайн',
    'global_chat_welcome': 'Добро пожаловать в глобальный чат водителей PoCho!',
    'global_chat_share_prices':
        'Поделитесь, где сейчас самые выгодные цены на топливо.',
    'global_chat_message': 'Сообщение...',
    'global_chat_no_messages': 'Сообщения не найдены',
    'global_chat_recording': 'Запись...',
    'global_chat_voice_message': 'Голосовое сообщение',
    'global_chat_video_message': 'Видео сообщение',
    'global_chat_photo': 'Фото',
    'global_chat_video': 'Видео',
    'global_chat_file': 'Файл',
    'global_chat_location': 'Местоположение',
    'global_chat_select_photo': 'Выбор фото',
    'global_chat_select_file': 'Выбор файла',
    'global_chat_sending_location': 'Отправка местоположения',
    'global_chat_notifications': 'Уведомления',
    'global_chat_notifications_enabled': 'Включены',
    'global_chat_sounds': 'Звуки',
    'global_chat_sounds_enabled': 'Включены',
    'global_chat_clear_history': 'Очистить историю',
    'global_chat_clear_history_subtitle': 'Удалить все сообщения',
    'global_chat_yesterday': 'Вчера',
    // Дополнительные ключи для глобального чата
    'global_chat_loading': 'Загрузка чата...',
    'global_chat_no_messages_title': 'Нет сообщений',
    'global_chat_start_conversation': 'Начните общение в глобальном чате',
    'global_chat_not_ready': 'Чат еще не готов. Подождите...',
    'global_chat_send_error': 'Не удалось отправить сообщение',
    'global_chat_enter_message': 'Введите сообщение...',
    'global_chat_block_user': 'Заблокировать пользователя',
    'global_chat_block_confirm':
        'Вы уверены, что хотите заблокировать {userName}? Вы не будете видеть его сообщения.',
    'global_chat_block': 'Заблокировать',
    'global_chat_user_blocked': 'Пользователь заблокирован',
    'global_chat_user_unblocked': 'Пользователь разблокирован',
    'global_chat_block_error': 'Не удалось заблокировать пользователя',
    'global_chat_unblock_error': 'Не удалось разблокировать пользователя',
    'global_chat_delete_message': 'Удалить сообщение',
    'global_chat_delete_confirm':
        'Вы уверены, что хотите удалить это сообщение? Это действие нельзя отменить. Сообщение будет удалено для всех пользователей.',
    'global_chat_delete': 'Удалить',
    'global_chat_message_deleted': 'Сообщение удалено',
    'global_chat_delete_error': 'Не удалось удалить сообщение',
    'global_chat_clear_history_title': 'Очистить историю',
    'global_chat_clear_confirm':
        'Вы уверены, что хотите очистить историю чата? Это действие нельзя отменить. История будет скрыта только для вас.',
    'global_chat_history_cleared': 'История очищена',
    'global_chat_clear_error': 'Не удалось очистить историю',
    'global_chat_blocked_users': 'Заблокированные пользователи',
    'global_chat_no_blocked_users': 'Нет заблокированных пользователей',
    'global_chat_user_profile': 'Профиль пользователя',
    'global_chat_search_messages': 'Поиск сообщений',
    'global_chat_search_hint': 'Введите запрос для поиска...',
    'global_chat_search': 'Поиск',
    'global_chat_search_query': 'Поиск: {query}',
    'global_chat_search_error': 'Ошибка поиска',
    'global_chat_attachment_image': 'Изображение',
    'global_chat_attachment_video': 'Видео',
    'global_chat_attachment_audio': 'Аудио',
    'global_chat_attachment_file': 'Файл',
    'global_chat_file_sent': 'Файл отправлен',
    'global_chat_file_error': 'Не удалось отправить файл',
    'global_chat_file_picker_error': 'Ошибка выбора файла',
    'global_chat_file_too_large': 'Размер файла превышает 50 MB',
    'global_chat_file_picker_unavailable':
        'Выбор файлов будет доступен после установки file_picker',
    'global_chat_init_error': 'Ошибка инициализации чата',
    'global_chat_connect_error': 'Не удалось подключиться к чату',
    'global_chat_load_error': 'Не удалось загрузить сообщения',
    'global_chat_only_own_messages': 'Вы можете удалить только свои сообщения',
    'global_chat_just_now': 'Только что',
    'global_chat_minutes_ago': '{minutes} мин назад',
    'global_chat_today': 'сегодня',
    'global_chat_yesterday_lower': 'вчера',
    'global_chat_days_ago': '{days} дн. назад',
    'global_chat_audio_playback':
        'Воспроизведение аудио будет доступно в будущих версиях',
    'global_chat_file_open': 'Открытие файла будет доступно в будущих версиях',
    // Уведомления
    'notifications_all': 'Все',
    'notifications_unread': 'Непрочитанные',
    'notifications_promotions': 'Акции',
    'notifications_prices': 'Цены',
    'notifications_info': 'Информационные',
    'notifications_messages': 'Сообщения',
    'notifications_public': 'Общие',
    'notifications_personal': 'Личные',
    'notifications_mark_all_read': 'Отметить все как прочитанные',
    'notifications_filters': 'Фильтры',
    'notifications_additional_filters': 'Дополнительные фильтры',
    'notifications_reset': 'Сбросить',
    'notifications_promotions_promo': 'Акции и промо',
    'notifications_price_changes': 'Изменения цен',
    'notifications_count': '{count} уведомлений',
    'notifications_loading': 'Загрузка уведомлений...',
    'notifications_error': 'Ошибка',
    'notifications_load_error':
        'Не удалось загрузить уведомления. Попробуйте позже.',
    'notifications_empty': 'Нет уведомлений',
    'notifications_public_empty': 'Здесь будут появляться общие уведомления',
    'notifications_personal_empty':
        'Здесь будут появляться ваши личные уведомления',
    'notifications_mark_read_error':
        'Не удалось отметить уведомление как прочитанное',
    'notifications_mark_all_read_success_public':
        'Все общие уведомления отмечены как прочитанные',
    'notifications_mark_all_read_success_personal':
        'Все личные уведомления отмечены как прочитанные',
    'notifications_mark_all_read_error':
        'Не удалось отметить все уведомления как прочитанные',
    'notifications_deleted': 'Уведомление удалено',
    'notifications_delete_error': 'Не удалось удалить уведомление',
    'notifications_try_again': 'Попробовать снова',
    'notifications_load_failed': 'Не удалось загрузить уведомления',
    'notifications_just_now': 'Только что',
    'notifications_minutes_ago': '{minutes} {form} назад',
    'notifications_minute_one': 'минуту',
    'notifications_minute_few': 'минуты',
    'notifications_minute_many': 'минут',
    'notifications_hours_ago': '{hours} {form} назад',
    'notifications_hour_one': 'час',
    'notifications_hour_few': 'часа',
    'notifications_hour_many': 'часов',
    'notifications_yesterday': 'Вчера',
    'notifications_days_ago': '{days} {form} назад',
    'notifications_day_one': 'день',
    'notifications_day_few': 'дня',
    'notifications_day_many': 'дней',
    'notifications_premium_title': 'Премиум подписка',
    'notifications_premium_subtitle':
        'Получайте уведомления о лучших ценах первыми',
    'notifications_invite_title': 'Пригласите друзей',
    'notifications_invite_subtitle': 'Получите бонусы за каждого друга',
    'notifications_ad': 'РЕКЛАМА',
    'cancel': 'Отмена',
    'ok': 'OK',
  },
  AppLanguage.uz: {
    'app_name': 'PoCho',
    'phone_auth_title': 'Telefon raqam orqali kirish',
    'phone_hint': 'Telefon raqami',
    'continue': 'Davom etish',
    'otp_title': 'Tasdiqlash kodi',
    'otp_subtitle': 'SMS dan 4 xonali kodni kiriting',
    'otp_sent_to': 'Kod quyidagi raqamga yuborildi',
    'verify': 'Tasdiqlash',
    'resend_code': 'Kodni qayta yuborish',
    'resend_in': 'Qayta yuborish',
    'seconds': 'son',
    'home': 'Bosh sahifa',
    'delivery': 'Yetkazib berish',
    'categories': 'Kategoriyalar',
    'map': 'Xarita',
    'chat': 'Chat',
    'favorites': 'Sevimlilar',
    'profile': 'Profil',
    'stations_nearby': 'Yaqin Yoqilg\'i shoxobchalari',
    'global_chat': 'Haydovchilar global chati',
    'language': 'Til',
    'russian': 'Rus tili',
    'uzbek': 'O\'zbek tili',
    'help': 'Yordam',
    'login_title': 'Kirish va ro\'yxatdan o\'tish',
    'phone_instruction': 'Davom etish uchun telefon raqamingizni kiriting',
    'agreement_text':
        'Mobil ilovada ro\'yxatdan o\'tish orqali siz shartlarga roziligingizni tasdiqlaysiz',
    'offer_link': 'Ochiq taklif va maxfiylik siyosati',
    'support_title': 'Qo\'llab-quvvatlash xizmati',
    'support_chat': 'Qo\'llab-quvvatlash chati',
    'support_chat_subtitle':
        'Qulay vaqtda yozing, mutaxassislarimiz imkoniyat bo\'lganda javob beradi',
    'support_welcome': 'Qo\'llab-quvvatlash chatiga xush kelibsiz',
    'support_welcome_subtitle': 'Savolingizni yozing, biz sizga yordam beramiz',
    'type_message': 'Xabar kiriting...',
    'enter_phone_error': 'Telefon raqamini kiriting',
    'invalid_phone_error': 'O\'zbek raqami formati noto\'g\'ri',
    'notifications': 'Xabarnomalar',
    'terms_and_privacy': 'Ochiq taklif va maxfiylik siyosati',
    'public_offer': 'Ochiq taklif',
    'privacy_policy': 'Maxfiylik siyosati',
    'contact_info': 'Aloqa ma\'lumotlari',
    'offer_intro':
        'Ushbu ochiq taklif (bundan buyon - "Taklif") PoCho mobil ilovasidan foydalanish bo\'yicha shartnoma tuzish uchun rasmiy taklifdir.',
    'offer_terms': '1. Atamalar va ta\'riflar',
    'offer_terms_content':
        'Ilova - mobil qurilmalarda yuklab olish va foydalanish uchun mavjud bo\'lgan PoCho mobil ilovasi.\n\nFoydalanuvchi - Ilovadan foydalanuvchi jismoniy shaxs.\n\nXizmat - Ilova orqali taqdim etiladigan xizmatlar majmui.',
    'offer_acceptance': '2. Shartlarni qabul qilish',
    'offer_acceptance_content':
        'Ilovadan foydalangan holda, Foydalanuvchi ushbu Taklif shartlari bilan tanishganini, ularni tushunganini va shartsiz qabul qilganini tasdiqlaydi. Agar Foydalanuvchi Taklif shartlari bilan rozi bo\'lmasa, u Ilovadan foydalanmasligi kerak.',
    'offer_services': '3. Taklif predmeti',
    'offer_services_content':
        'PoCho Foydalanuvchiga yoqilg\'i shoxobchalari, restoranlar, STO, avtomoika va elektr shoxobchalarni qidirish, narxlar, sharhlar va Ilova orqali mavjud bo\'lgan boshqa xizmatlar haqida ma\'lumot olish imkoniyatini taqdim etadi.',
    'offer_responsibility': '4. Tomonlarning javobgarligi',
    'offer_responsibility_content':
        'PoCho uchinchi shaxslar (yoqilg\'i shoxobchalari, restoranlar va boshqalar) tomonidan taqdim etilgan ma\'lumotlarning to\'g\'riligi uchun javobgar emas. Foydalanuvchi Ilovadan o\'z xavfi-xatarida foydalanadi.',
    'offer_changes': '5. Shartlarni o\'zgartirish',
    'offer_changes_content':
        'PoCho ushbu Taklif shartlarini istalgan vaqtda o\'zgartirish huquqini o\'zida saqlaydi. O\'zgarishlar Ilovada e\'lon qilingan kundan boshlab kuchga kiradi.',
    'privacy_intro':
        'PoCho foydalanuvchilarning shaxsiy ma\'lumotlarini himoya qilishga jiddiy yondashadi. Ushbu siyosat biz qanday ma\'lumotlarni to\'playmiz, qanday foydalanamiz va himoya qilamizni tushuntiradi.',
    'privacy_data_collection': '1. Ma\'lumotlar to\'planishi',
    'privacy_data_collection_content':
        'Biz quyidagi ma\'lumotlarni to\'playmiz:\n- Telefon raqami (autentifikatsiya uchun)\n- Geolokatsiya ma\'lumotlari (xizmatlarni topish uchun)\n- Foydalanish statistikasi\n- Qidiruv so\'rovlari',
    'privacy_data_usage': '2. Ma\'lumotlardan foydalanish',
    'privacy_data_usage_content':
        'To\'plangan ma\'lumotlar quyidagi maqsadlarda ishlatiladi:\n- Xizmatlarni taqdim etish va yaxshilash\n- Foydalanuvchi tajribasini shaxsiylashtirish\n- Texnik yordam ko\'rsatish\n- Xavfsizlikni ta\'minlash',
    'privacy_data_protection': '3. Ma\'lumotlarni himoya qilish',
    'privacy_data_protection_content':
        'Biz zamonaviy kriptografiya va xavfsizlik texnologiyalaridan foydalanib, foydalanuvchi ma\'lumotlarini himoya qilamiz. Ma\'lumotlar uchinchi shaxslarga oshkor qilinmaydi.',
    'privacy_user_rights': '4. Foydalanuvchi huquqlari',
    'privacy_user_rights_content':
        'Har bir foydalanuvchi quyidagi huquqlarga ega:\n- O\'z ma\'lumotlariga kirish\n- Ma\'lumotlarni tahrirlash\n- Ma\'lumotlarni o\'chirish\n- Ma\'lumotlardan foydalanishga qarshi chiqish',
    'privacy_cookies': '5. Cookie va texnologiyalar',
    'privacy_cookies_content':
        'Biz foydalanish statistikasi va xizmatlarni yaxshilash uchun cookie va shunga o\'xshash texnologiyalardan foydalanamiz.',
    'contact_intro':
        'Agar sizda savollar yoki takliflar bo\'lsa, biz bilan bog\'laning:',
    'contact_email': 'Elektron pochta',
    'contact_phone': 'Telefon',
    'contact_address': 'Manzil',
    'contact_address_content': 'Toshkent shahri, Mustaqillik ko\'chasi, 10',
    'auth_instruction_title': 'Autentifikatsiya bo\'yicha ko\'rsatma',
    // Профиль
    'profile_user': 'Foydalanuvchi',
    'profile_beginner': 'Yangi',
    'profile_stations_visited': 'Shoxobchalar',
    'profile_favorites_count': 'Sevimlilar',
    'profile_rating': 'Reyting',
    'profile_load_error': 'Profilni yuklab bo\'lmadi',
    'profile_try_again': 'Qayta urinish',
    'profile_balance': 'Balans',
    'profile_my_orders': 'Mening buyurtmalarim',
    'profile_main_info': 'Asosiy ma\'lumotlar',
    'profile_name': 'Ism',
    'profile_phone': 'Telefon',
    'profile_email': 'Email',
    'profile_not_specified': 'Ko\'rsatilmagan',
    'profile_document_verification': 'Hujjatlarni tasdiqlash',
    'profile_passport': 'Pasport',
    'profile_driving_license': 'Haydovchilik guvohnomasi',
    'profile_settings': 'Sozlamalar',
    'profile_support': 'Texnik yordam',
    'profile_logout': 'Chiqish',
    'profile_select_photo': 'Rasmni tanlang',
    'profile_gallery': 'Galereya',
    'profile_camera': 'Kamera',
    'profile_delete_photo': 'Rasmni o\'chirish',
    'profile_select_passport_photo': 'Pasport rasmini tanlang',
    'profile_select_license_photo': 'Haydovchilik guvohnomasi rasmini tanlang',
    'profile_avatar_updated': 'Avatar muvaffaqiyatli yangilandi',
    'profile_passport_uploaded': 'Pasport rasmi muvaffaqiyatli yuklandi',
    'profile_license_uploaded':
        'Haydovchilik guvohnomasi rasmi muvaffaqiyatli yuklandi',
    'profile_upload_error': 'Yuklashda xatolik',
    'profile_image_error': 'Rasmni tanlab bo\'lmadi',
    'profile_unsupported_format':
        'Faqat JPEG, PNG, WEBP formatlari qo\'llab-quvvatlanadi',
    'profile_document_not_uploaded': 'Hujjat yuklanmagan',
    'profile_click_to_upload': 'Yuklash uchun bosing',
    'notifications_enabled': 'Xabarnomalar yoqilgan',
    'notifications_disabled': 'Xabarnomalar o\'chirilgan',
    // Главная страница
    'search_stations_hint': 'Yoqilg\'i shoxobchalarni qidirish...',
    'retry': 'Qayta urinish',
    'no_stations_found': 'Yoqilg\'i shoxobchalari topilmadi',
    'removed_from_favorites': 'Sevimlilardan olib tashlandi',
    'added_to_favorites': 'Sevimlilarga qo\'shildi',
    'failed_to_change_favorite': 'Sevimlilar holatini o\'zgartirib bo\'lmadi',
    'error_changing_favorite': 'Sevimlilarni o\'zgartirishda xatolik',
    // Фильтры
    'filters': 'Filtrlash',
    'fuel_type': 'Yoqilg\'i turi',
    'min_rating': 'Minimal reyting',
    'max_price': 'Maksimal narx',
    'additional': 'Qo\'shimcha',
    'open_24_7': 'Kechayu-kunduz ishlaydi',
    'has_promotions': 'Aksiyalar mavjud',
    'reset': 'Tozalash',
    'apply': 'Qo\'llash',
    'all': 'Barchasi',
    'price_up_to_10000': '10 000 gacha',
    'price_up_to_12000': '12 000 gacha',
    'price_up_to_15000': '15 000 gacha',
    'price_up_to_20000': '20 000 gacha',
    // Рекламные баннеры
    'promo_discount_10': 'Barcha yoqilg\'i turlarida 10% chegirma',
    'promo_until_weekend': 'Hafta oxirigacha',
    'promo_free_wash': 'To\'ldirishda bepul yuvish',
    'promo_from_50_liters': '50 litrdan boshlab',
    'promo_bonus_points': 'Har bir to\'ldirish uchun bonus ballar',
    'promo_accumulate_exchange': 'Yig\'ib, almashtiring',
    'auth_instruction_step1_title': 'Telefon raqamini kiriting',
    'auth_instruction_step1_description':
        'Telefon raqamingizni XX XXX XX XX formatida kiriting. Raqam to\'g\'ri ko\'rsatilganligiga ishonch hosil qiling.',
    'auth_instruction_step2_title': 'Raqamni tasdiqlang',
    'auth_instruction_step2_description':
        'SMS tasdiqlash kodi yuborish uchun "Davom etish" tugmasini bosing.',
    'auth_instruction_step3_title': 'Tasdiqlash kodini kiriting',
    'auth_instruction_step3_description':
        'Telefoningizga kelgan SMS xabardagi kodni kiriting. Kod cheklangan vaqt davomida amal qiladi.',
    'auth_instruction_step4_title': 'Tayyor!',
    'auth_instruction_step4_description':
        'Muvaffaqiyatli autentifikatsiyadan so\'ng siz ilovaning barcha funksiyalaridan foydalanishingiz mumkin bo\'ladi.',
    'error': 'Xatolik',
    // Доставка
    'delivery_location_permission':
        'Xaritada joylashuvingizni ko\'rsatish uchun geolokatsiyaga kirish ruxsati kerak. Iltimos, ilova sozlamalarida ruxsat bering.',
    'delivery_location_permission_required': 'Joylashuvga kirish ruxsati kerak',
    'delivery_location_permission_required_full':
        'Joylashuvingizni ko\'rsatish uchun geolokatsiyaga kirish ruxsati kerak',
    'delivery_finding_location': 'Joylashuv aniqlanmoqda...',
    'delivery_location_found': 'Joylashuv topildi',
    'delivery_location_failed':
        'Joylashuvni aniqlab bo\'lmadi. Ruxsatlarni tekshiring.',
    'delivery_find_me': 'Menni top',
    'delivery_from_to': 'Qayerdan va qayerga',
    'delivery_from_to_hint':
        'Xaritada nuqtalarni ko\'rsating va kerak bo\'lsa manzillarni yozing',
    'delivery_from': 'Qayerdan',
    'delivery_to': 'Qayerga',
    'delivery_pickup_address': 'Yuborish manzili',
    'delivery_delivery_address': 'Qabul qilish manzili',
    'delivery_address_hint': 'Shahar, ko\'cha, uy',
    'delivery_map_point': 'Xaritadagi nuqta',
    'delivery_specify_pickup':
        'Yuborish manzilini yoki xaritadagi nuqtani ko\'rsating',
    'delivery_specify_delivery':
        'Qabul qilish manzilini yoki xaritadagi nuqtani ko\'rsating',
    'delivery_specify_both_points':
        'Narxni hisoblash uchun ikkala manzil uchun ham xaritada nuqtalarni ko\'rsating',
    'delivery_calculate_price': 'Narxni hisoblash',
    'delivery_change_addresses': 'Manzillarni o\'zgartirish',
    'delivery_price': 'Yetkazib berish narxi',
    'delivery_parcel_description': 'Yuk tavsifi',
    'delivery_parcel_description_hint': 'Masalan: Hujjatlar, kiyim',
    'delivery_estimated_value': 'Taxminiy qiymat (so\'m)',
    'delivery_optional': 'Ixtiyoriy',
    'delivery_create_order': 'Buyurtma rasmiylashtirish',
    'delivery_order_created': 'Buyurtma yaratildi',
    'delivery_courier_contact':
        'Kuryer yaqin vaqtda yetkazib berish tafsilotlarini aniqlash uchun siz bilan bog\'lanadi.',
    'delivery_understood': 'Tushundim',
    'delivery_failed_to_calculate': 'Narxni hisoblab bo\'lmadi',
    'delivery_failed_to_create': 'Buyurtma yaratib bo\'lmadi',
    'delivery_my_orders': 'Mening buyurtmalarim',
    'delivery_no_orders': 'Hozircha buyurtmalar yo\'q',
    'delivery_create_on_map': 'Xaritada yetkazib berishni rasmiylashtiring',
    'delivery_order': 'Buyurtma',
    'delivery_order_details': 'Buyurtma tafsilotlari',
    'delivery_order_not_found': 'Buyurtma topilmadi',
    'delivery_timeline': 'Vaqt jadvali',
    'delivery_order_created_status': 'Buyurtma yaratildi',
    'delivery_accepted_by_driver': 'Haydovchi tomonidan qabul qilindi',
    'delivery_cargo_received': 'Yuk qabul qilindi',
    'delivery_delivered': 'Yetkazib berildi',
    'delivery_cancelled': 'Bekor qilindi',
    'delivery_address_not_specified': 'Manzil ko\'rsatilmagan',
    'delivery_cargo_description_label': 'Yuk tavsifi',
    'delivery_weight': 'Og\'irlik',
    'delivery_volume': 'Hajm',
    'delivery_distance': 'Masofa',
    'delivery_cost': 'Narx',
    'delivery_payment_method': 'To\'lov usuli',
    'delivery_client_comment': 'Mijoz izohi',
    'delivery_driver_comment': 'Haydovchi izohi',
    'delivery_driver': 'Haydovchi',
    'delivery_cancel_reason': 'Bekor qilish sababi',
    'delivery_accept_order': 'Buyurtmani qabul qilish',
    'delivery_driver_on_way': 'Haydovchi buyurtma uchun ketmoqda',
    'delivery_going_for_order': 'Buyurtma uchun ketmoqdaman',
    'delivery_on_way_to_recipient': 'Qabul qiluvchiga yo\'lda',
    'delivery_failed_to_deliver': 'Yetkazib berib bo\'lmadi',
    'delivery_delivered_status': 'Yetkazib berildi',
    'delivery_order_successfully_delivered':
        'Buyurtma muvaffaqiyatli yetkazib berildi',
    'delivery_order_cancelled': 'Buyurtma bekor qilindi',
    'delivery_failed_to_deliver_order': 'Buyurtmani yetkazib berib bo\'lmadi',
    'delivery_update_status': 'Holatni yangilash',
    'delivery_cancel_order': 'Buyurtmani bekor qilish',
    'delivery_cancel_reason_optional': 'Bekor qilish sababi (ixtiyoriy)',
    'delivery_comment_optional': 'Izoh (ixtiyoriy)',
    'delivery_specify_cancel_reason': 'Bekor qilish sababini ko\'rsating...',
    'delivery_add_comment': 'Izoh qo\'shing...',
    'delivery_confirm': 'Tasdiqlash',
    'delivery_cancel': 'Bekor qilish',
    'delivery_failed_to_load_orders': 'Buyurtmalarni yuklab bo\'lmadi',
    'delivery_failed_to_load_order': 'Buyurtmani yuklab bo\'lmadi',
    'delivery_order_accepted': 'Buyurtma muvaffaqiyatli qabul qilindi!',
    'delivery_failed_to_accept': 'Buyurtmani qabul qilib bo\'lmadi',
    'delivery_not_approved':
        'Arizangiz hali administrator tomonidan tasdiqlanmagan. Hujjatlarni tekshirishni kutib turing.',
    'delivery_rejected':
        'Arizangiz administrator tomonidan rad etildi. Qo\'llab-quvvatlash xizmatiga murojaat qiling.',
    'delivery_blocked':
        'Hisobingiz vaqtincha bloklangan. Qo\'llab-quvvatlash xizmatiga murojaat qiling.',
    'delivery_not_online':
        'Buyurtmalarni qabul qilish uchun onlayn bo\'lishingiz kerak.',
    'delivery_already_accepted':
        'Bu buyurtma boshqa haydovchi tomonidan allaqachon qabul qilingan.',
    'delivery_status_updated': 'Buyurtma holati yangilandi',
    'delivery_failed_to_update_status': 'Holatni yangilab bo\'lmadi',
    'delivery_no_permission_update':
        'Bu buyurtma holatini yangilash huquqiga ega emassiz',
    'delivery_invalid_status_transition':
        'Holatlar o\'rtasidagi o\'tish noto\'g\'ri. Joriy buyurtma holatini tekshiring.',
    'delivery_cannot_cancel_after_pickup':
        'Haydovchi tomonidan yuk qabul qilingandan keyin buyurtmani bekor qilib bo\'lmaydi',
    'delivery_pick_on_map': 'Xaritada ko\'rsatish',
    'delivery_map_picker_title': 'Xaritada ko\'rsatish',
    'delivery_select': 'Tanlash',
    'delivery_tap_map_to_select': 'Nuqtani ko\'rsatish uchun xaritaga bosing',
    'delivery_balance': 'Yetkazib berish balansi',
    'delivery_current_balance': 'Joriy balans',
    'delivery_transaction_history': 'Operatsiyalar tarixi',
    'delivery_no_transactions': 'Hozircha operatsiyalar yo\'q',
    'delivery_load_more': 'Yana yuklash',
    'delivery_failed_to_load_balance': 'Balansni yuklab bo\'lmadi',
    'delivery_failed_to_load_history': 'Tarixni yuklab bo\'lmadi',
    'delivery_failed_to_load_more': 'Qo\'shimcha tarixni yuklab bo\'lmadi',
    'delivery_today': 'Bugun',
    'delivery_yesterday': 'Kecha',
    'delivery_regions_uzbekistan': 'O\'zbekiston viloyatlari bo\'yicha',
    'delivery_time_1_3_days': '1-3 kun',
    'delivery_service_fee_text':
        'Narxga buyurtma summasi bo\'yicha 0% (3% o\'rniga) xizmat to\'lovi kiritilgan',
    'delivery_go_to_order_form': 'Buyurtma formasiga o\'tish',
    // Категории
    'category_restaurants': 'Restoranlar',
    'category_car_service': 'STO',
    'category_car_wash': 'Moykalar',
    'category_charging_stations': 'Elektrozapravkalar',
    // Фильтры
    'filter_all': 'Barchasi',
    'filter_nearby': 'Yaqin',
    'filter_with_promotions': 'Aksiyalar bilan',
    'filter_high_rating': 'Yuqori reyting',
    'filter_with_parking': 'Parkovka bilan',
    'filter_with_wifi': 'Wi-Fi bilan',
    'filter_cheap': 'Arzon',
    'filter_premium': 'Premium',
    'filter_fast_charging': 'Tez zaryadlash',
    'filter_available': 'Mavjud',
    'filter_24_7': '24/7',
    // Кухни
    'cuisine_uzbek': 'O\'zbek',
    'cuisine_european': 'Yevropa',
    'cuisine_japanese': 'Yapon',
    'cuisine_italian': 'Italyan',
    'cuisine_chinese': 'Xitoy',
    'cuisine_american': 'Amerika',
    'cuisine_french': 'Fransuz',
    'cuisine_indian': 'Hind',
    'cuisine_georgian': 'Gruzin',
    // Ценовые диапазоны
    'price_economy': 'Iqtisodiy',
    'price_standard': 'Standart',
    'price_all_prices': 'Barcha narxlar',
    'price_all_powers': 'Barcha quvvatlar',
    // Другие тексты категорий
    'select_what_you_need_now': 'Hozir nima kerakligini tanlang',
    'search_restaurants': 'Restoranlarni qidirish...',
    'search_car_service': 'STO qidirish...',
    'search_car_wash': 'Moykalarni qidirish...',
    'search_charging_stations': 'Elektrozapravkalarni qidirish...',
    'loading_restaurants': 'Restoranlar yuklanmoqda...',
    'loading_car_service': 'STO yuklanmoqda...',
    'loading_car_wash': 'Moykalar yuklanmoqda...',
    'loading_charging_stations': 'Elektrozapravkalar yuklanmoqda...',
    'no_restaurants_found': 'Restoranlar topilmadi',
    'no_car_service_found': 'STO topilmadi',
    'no_car_wash_found': 'Moykalar topilmadi',
    'no_charging_stations_found': 'Elektrozapravkalar topilmadi',
    'cuisine_type': 'Oshxona turi',
    'price_range': 'Narx diapazoni',
    'service_type': 'Xizmat turi',
    'try_changing_filters': 'Filtrlarni o\'zgartirishni harakat qiling',
    'on_map': 'Xaritada',
    'ai_assistant': 'AI yordamchi',
    // ИИ ассистент
    'ai_assistant_title': 'AI Yordamchi',
    'ai_assistant_subtitle': 'Har doim yordamga tayyor',
    'ai_quick_question_cheap_station': 'Qayerda eng arzon zapravka yaqin?',
    'ai_quick_question_fast_route': 'Qaysi marshrut eng tez?',
    'ai_quick_question_fuel_quality': 'Yoqilg\'i sifati haqida gapiring',
    'ai_quick_question_fuel_saving': 'Yoqilg\'i tejash bo\'yicha maslahatlar',
    'ai_welcome_message':
        'Salom! Men PoCho AI yordamchisiman. Sizga eng yaxshi zapravkalarni topishda, marshrut qurishda, yoqilg\'i narxlari haqida bilishda va tejash bo\'yicha maslahatlar berishda yordam beraman. Qanday yordam bera olaman?',
    'ai_quick_questions': 'Tezkor savollar:',
    'ai_ask_question': 'Savol bering...',
    'ai_send': 'Yuborish',
    'ai_cancel': 'Bekor qilish',
    'ai_voice_recording': 'Ovozli xabar yozilmoqda...',
    'ai_voice_message': 'Ovozli xabar',
    'ai_history': 'Tarix',
    'ai_menu': 'Menyu',
    'ai_clear_history': 'Tarixni tozalash',
    'ai_clear_history_confirm': 'Tarixni tozalash?',
    'ai_clear_history_content':
        'Barcha xabarlar o\'chiriladi. Bu harakatni bekor qilib bo\'lmaydi.',
    'ai_clear_all': 'Hammasini tozalash',
    'ai_history_empty': 'Tarix bo\'sh',
    'ai_history_cleared': 'Tarix tozalandi',
    'ai_feedback': 'Fikr bildirish',
    'ai_help': 'Yordam',
    'ai_dialog_history': 'Suhbatlar tarixi',
    'ai_dialog_search_stations': 'Zapravkalarni qidirish',
    'ai_dialog_fuel_saving': 'Tejash bo\'yicha maslahatlar',
    'ai_dialog_route': 'Marshrut qurish',
    // Глобальный чат
    'global_chat_online': 'Onlayn',
    'global_chat_welcome':
        'PoCho haydovchilarining global chatiga xush kelibsiz!',
    'global_chat_share_prices':
        'Hozir qayerda eng foydali yoqilg\'i narxlari borligini baham ko\'ring.',
    'global_chat_message': 'Xabar...',
    'global_chat_no_messages': 'Xabarlar topilmadi',
    'global_chat_recording': 'Yozilmoqda...',
    'global_chat_voice_message': 'Ovozli xabar',
    'global_chat_video_message': 'Video xabar',
    'global_chat_photo': 'Foto',
    'global_chat_video': 'Video',
    'global_chat_file': 'Fayl',
    'global_chat_location': 'Joylashuv',
    'global_chat_select_photo': 'Foto tanlash',
    'global_chat_select_file': 'Fayl tanlash',
    'global_chat_sending_location': 'Joylashuv yuborilmoqda',
    'global_chat_notifications': 'Bildirishnomalar',
    'global_chat_notifications_enabled': 'Yoqilgan',
    'global_chat_sounds': 'Ovozlar',
    'global_chat_sounds_enabled': 'Yoqilgan',
    'global_chat_clear_history': 'Tarixni tozalash',
    'global_chat_clear_history_subtitle': 'Barcha xabarlarni o\'chirish',
    'global_chat_yesterday': 'Kecha',
    // Дополнительные ключи для глобального чата
    'global_chat_loading': 'Chat yuklanmoqda...',
    'global_chat_no_messages_title': 'Xabarlar yo\'q',
    'global_chat_start_conversation': 'Global chatda suhbatni boshlang',
    'global_chat_not_ready': 'Chat hali tayyor emas. Kuting...',
    'global_chat_send_error': 'Xabar yuborib bo\'lmadi',
    'global_chat_enter_message': 'Xabar kiriting...',
    'global_chat_block_user': 'Foydalanuvchini bloklash',
    'global_chat_block_confirm':
        '{userName} ni bloklashni xohlaysizmi? Siz uning xabarlarini ko\'rmaysiz.',
    'global_chat_block': 'Bloklash',
    'global_chat_user_blocked': 'Foydalanuvchi bloklandi',
    'global_chat_user_unblocked': 'Foydalanuvchi blokdan olindi',
    'global_chat_block_error': 'Foydalanuvchini bloklab bo\'lmadi',
    'global_chat_unblock_error': 'Foydalanuvchini blokdan olib bo\'lmadi',
    'global_chat_delete_message': 'Xabarni o\'chirish',
    'global_chat_delete_confirm':
        'Bu xabarni o\'chirishni xohlaysizmi? Bu amalni bekor qilib bo\'lmaydi. Xabar barcha foydalanuvchilar uchun o\'chiriladi.',
    'global_chat_delete': 'O\'chirish',
    'global_chat_message_deleted': 'Xabar o\'chirildi',
    'global_chat_delete_error': 'Xabarni o\'chirib bo\'lmadi',
    'global_chat_clear_history_title': 'Tarixni tozalash',
    'global_chat_clear_confirm':
        'Chat tarixini tozalashni xohlaysizmi? Bu amalni bekor qilib bo\'lmaydi. Tarix faqat siz uchun yashirinadi.',
    'global_chat_clear': 'Tozalash',
    'global_chat_history_cleared': 'Tarix tozalandi',
    'global_chat_clear_error': 'Tarixni tozalab bo\'lmadi',
    'global_chat_blocked_users': 'Bloklangan foydalanuvchilar',
    'global_chat_no_blocked_users': 'Bloklangan foydalanuvchilar yo\'q',
    'global_chat_user_profile': 'Foydalanuvchi profili',
    'global_chat_search_messages': 'Xabarlarni qidirish',
    'global_chat_search_hint': 'Qidirish uchun so\'rov kiriting...',
    'global_chat_search': 'Qidirish',
    'global_chat_search_query': 'Qidirish: {query}',
    'global_chat_search_error': 'Qidirish xatosi',
    'global_chat_attachment_image': 'Rasm',
    'global_chat_attachment_video': 'Video',
    'global_chat_attachment_audio': 'Audio',
    'global_chat_attachment_file': 'Fayl',
    'global_chat_file_sent': 'Fayl yuborildi',
    'global_chat_file_error': 'Faylni yuborib bo\'lmadi',
    'global_chat_file_picker_error': 'Fayl tanlash xatosi',
    'global_chat_file_too_large': 'Fayl hajmi 50 MB dan oshadi',
    'global_chat_file_picker_unavailable':
        'Fayl tanlash file_picker o\'rnatilgandan keyin mavjud bo\'ladi',
    'global_chat_init_error': 'Chatni ishga tushirish xatosi',
    'global_chat_connect_error': 'Chatga ulanib bo\'lmadi',
    'global_chat_load_error': 'Xabarlarni yuklab bo\'lmadi',
    'global_chat_only_own_messages':
        'Siz faqat o\'z xabarlaringizni o\'chirishingiz mumkin',
    'global_chat_just_now': 'Hozirgina',
    'global_chat_minutes_ago': '{minutes} daqiqa oldin',
    'global_chat_today': 'bugun',
    'global_chat_yesterday_lower': 'kecha',
    'global_chat_days_ago': '{days} kun oldin',
    'global_chat_audio_playback':
        'Audio ijro etish kelajakdagi versiyalarda mavjud bo\'ladi',
    'global_chat_file_open':
        'Faylni ochish kelajakdagi versiyalarda mavjud bo\'ladi',
    // Уведомления
    'notifications_all': 'Barchasi',
    'notifications_unread': 'O\'qilmagan',
    'notifications_promotions': 'Aksiyalar',
    'notifications_prices': 'Narxlar',
    'notifications_info': 'Ma\'lumot',
    'notifications_messages': 'Xabarlar',
    'notifications_public': 'Umumiy',
    'notifications_personal': 'Shaxsiy',
    'notifications_mark_all_read': 'Barchasini o\'qilgan deb belgilash',
    'notifications_filters': 'Filtrlash',
    'notifications_additional_filters': 'Qo\'shimcha filtrlash',
    'notifications_reset': 'Tozalash',
    'notifications_promotions_promo': 'Aksiyalar va promo',
    'notifications_price_changes': 'Narx o\'zgarishlari',
    'notifications_count': '{count} bildirishnoma',
    'notifications_loading': 'Bildirishnomalar yuklanmoqda...',
    'notifications_error': 'Xato',
    'notifications_load_error':
        'Bildirishnomalarni yuklab bo\'lmadi. Keyinroq urinib ko\'ring.',
    'notifications_empty': 'Bildirishnomalar yo\'q',
    'notifications_public_empty':
        'Bu yerda umumiy bildirishnomalar paydo bo\'ladi',
    'notifications_personal_empty':
        'Bu yerda sizning shaxsiy bildirishnomalaringiz paydo bo\'ladi',
    'notifications_mark_read_error':
        'Bildirishnomani o\'qilgan deb belgilab bo\'lmadi',
    'notifications_mark_all_read_success_public':
        'Barcha umumiy bildirishnomalar o\'qilgan deb belgilandi',
    'notifications_mark_all_read_success_personal':
        'Barcha shaxsiy bildirishnomalar o\'qilgan deb belgilandi',
    'notifications_mark_all_read_error':
        'Barcha bildirishnomalarni o\'qilgan deb belgilab bo\'lmadi',
    'notifications_deleted': 'Bildirishnoma o\'chirildi',
    'notifications_delete_error': 'Bildirishnomani o\'chirib bo\'lmadi',
    'notifications_try_again': 'Qayta urinib ko\'ring',
    'notifications_load_failed': 'Bildirishnomalarni yuklab bo\'lmadi',
    'notifications_just_now': 'Hozirgina',
    'notifications_minutes_ago': '{minutes} {form} oldin',
    'notifications_minute_one': 'daqiqa',
    'notifications_minute_few': 'daqiqa',
    'notifications_minute_many': 'daqiqa',
    'notifications_hours_ago': '{hours} {form} oldin',
    'notifications_hour_one': 'soat',
    'notifications_hour_few': 'soat',
    'notifications_hour_many': 'soat',
    'notifications_yesterday': 'Kecha',
    'notifications_days_ago': '{days} {form} oldin',
    'notifications_day_one': 'kun',
    'notifications_day_few': 'kun',
    'notifications_day_many': 'kun',
    'notifications_premium_title': 'Premium obuna',
    'notifications_premium_subtitle':
        'Eng yaxshi narxlar haqidagi bildirishnomalarni birinchi bo\'lib oling',
    'notifications_invite_title': 'Do\'stlarni taklif qiling',
    'notifications_invite_subtitle': 'Har bir do\'st uchun bonus oling',
    'notifications_ad': 'REKLAMA',
    'cancel': 'Bekor qilish',
    'ok': 'OK',
  },
};
